/** squadId → "{folder}/{stem}" (generated by scripts/importEspn.ts as logoIndex.json). */
export type LogoIndex = Record<string, string>;

/** Crest URL for a squad, or undefined when the club has no crest file (the UI then draws a shield). */
export function logoUrlFromIndex(index: LogoIndex, squadId: string): string | undefined {
  const path = index[squadId];
  return path ? `/api/logos/${path}` : undefined;
}
