// AUTO-GENERATED by scripts/extract-club-data.mjs
// Source: TouchLines src/Data/squads/la_liga/{541,529}.json
// Do not edit by hand — re-run the script when the game data changes.

export interface PlayerStats {
  passing: number; vision: number; finishing: number; dribbling: number;
  speed: number; acceleration: number; tackling: number; pressing: number;
  stamina: number; heading: number; strength: number;
  reflex: number; jump: number;
}

export interface ClubPlayer {
  id: string;
  name: string;
  fullName: string;
  age: number;
  preferredFoot: "left" | "right";
  positions: string[];
  stats: PlayerStats;
  profile: { summary: string; archetype: string };
  rating: number;
  slot?: { role: string; x: number; y: number };
}

export interface ClubVenue {
  name: string;
  city: string;
  capacity: number;
  surface: string;
}

export interface Club {
  id: string;
  slug: string;
  name: string;
  code: string;
  colors: [string, string];
  logo: string;          // relative to /public
  founded: number;
  country: string;
  venue: ClubVenue;
  coach: { id: number; name: string };
  starting11: ClubPlayer[];
  bench: ClubPlayer[];
}

export const REAL_MADRID: Club = {
  "id": "541",
  "slug": "real_madrid",
  "name": "Real Madrid",
  "code": "REA",
  "colors": [
    "#FFFFFF",
    "#FEBE10"
  ],
  "logo": "logos/la_liga/real_madrid.svg",
  "founded": 1902,
  "country": "Spain",
  "venue": {
    "name": "Estadio Santiago Bernabéu",
    "city": "Madrid",
    "capacity": 85454,
    "surface": "grass"
  },
  "coach": {
    "id": 25679,
    "name": "Alvaro Arbeloa"
  },
  "starting11": [
    {
      "id": "player_3594",
      "name": "T. Courtois",
      "fullName": "Thibaut Nicolas Marc Courtois",
      "age": 33,
      "preferredFoot": "right",
      "positions": [
        "GK"
      ],
      "stats": {
        "passing": 4,
        "vision": 2,
        "finishing": 0,
        "dribbling": 1,
        "speed": 2,
        "acceleration": 2,
        "tackling": 1,
        "pressing": 1,
        "stamina": 3,
        "heading": 4,
        "strength": 3,
        "reflex": 7,
        "jump": 5
      },
      "profile": {
        "summary": "Commanding goalkeeper who organises the back line effectively.",
        "archetype": "Sweeper-keeper"
      },
      "rating": 4.5,
      "slot": {
        "role": "GK",
        "x": 5,
        "y": 37
      }
    },
    {
      "id": "player_3601",
      "name": "T. Alexander-Arnold",
      "fullName": "Trent John Alexander-Arnold",
      "age": 27,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 2,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 6,
        "tackling": 6,
        "pressing": 4,
        "stamina": 6,
        "heading": 3,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Energetic full-back who contributes at both ends of the pitch.",
        "archetype": "Defensive full-back"
      },
      "rating": 4.8,
      "slot": {
        "role": "LB",
        "x": 18,
        "y": 11
      }
    },
    {
      "id": "player_3605",
      "name": "Éder Militão",
      "fullName": "Éder Gabriel Militão",
      "age": 27,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 6,
        "vision": 4,
        "finishing": 3,
        "dribbling": 5,
        "speed": 5,
        "acceleration": 7,
        "tackling": 4,
        "pressing": 4,
        "stamina": 5,
        "heading": 3,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Solid defender who gets forward to support attacks when possible.",
        "archetype": "Attacking wing-back"
      },
      "rating": 4.8,
      "slot": {
        "role": "CB",
        "x": 22,
        "y": 28
      }
    },
    {
      "id": "player_3607",
      "name": "Fran García",
      "fullName": "Francisco José García Torres",
      "age": 26,
      "preferredFoot": "left",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 2,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 7,
        "tackling": 5,
        "pressing": 4,
        "stamina": 6,
        "heading": 3,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Solid defender who gets forward to support attacks when possible.",
        "archetype": "Modern full-back"
      },
      "rating": 4.8,
      "slot": {
        "role": "CB",
        "x": 22,
        "y": 46
      }
    },
    {
      "id": "player_3611",
      "name": "F. Mendy",
      "fullName": "Ferland Sinna Mendy",
      "age": 30,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 5,
        "vision": 3,
        "finishing": 1,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 6,
        "tackling": 4,
        "pressing": 4,
        "stamina": 5,
        "heading": 3,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Solid defender who gets forward to support attacks when possible.",
        "archetype": "Inverted full-back"
      },
      "rating": 4,
      "slot": {
        "role": "RB",
        "x": 18,
        "y": 63
      }
    },
    {
      "id": "player_3620",
      "name": "A. Güler",
      "fullName": "Arda Güler",
      "age": 20,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 5,
        "vision": 6,
        "finishing": 6,
        "dribbling": 7,
        "speed": 7,
        "acceleration": 8,
        "tackling": 2,
        "pressing": 3,
        "stamina": 6,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Skilful winger who combines dribbling ability with end product.",
        "archetype": "Inside forward"
      },
      "rating": 5.5,
      "slot": {
        "role": "CDM",
        "x": 38,
        "y": 37
      }
    },
    {
      "id": "player_3614",
      "name": "J. Bellingham",
      "fullName": "Jude Victor William Bellingham",
      "age": 22,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 6,
        "vision": 4,
        "finishing": 5,
        "dribbling": 7,
        "speed": 6,
        "acceleration": 8,
        "tackling": 2,
        "pressing": 3,
        "stamina": 5,
        "heading": 3,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Pacy wide player who stretches defences with off-the-ball runs.",
        "archetype": "Inverted winger"
      },
      "rating": 5.1,
      "slot": {
        "role": "CM",
        "x": 50,
        "y": 24
      }
    },
    {
      "id": "player_3625",
      "name": "F. Valverde",
      "fullName": "Federico Santiago Valverde Dipetta",
      "age": 27,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 2,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 7,
        "tackling": 5,
        "pressing": 4,
        "stamina": 6,
        "heading": 3,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Energetic full-back who contributes at both ends of the pitch.",
        "archetype": "Overlapping full-back"
      },
      "rating": 4.8,
      "slot": {
        "role": "CM",
        "x": 50,
        "y": 50
      }
    },
    {
      "id": "player_3629",
      "name": "Franco Mastantuono",
      "fullName": "Franco Mastantuono",
      "age": 18,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 5,
        "vision": 5,
        "finishing": 5,
        "dribbling": 8,
        "speed": 8,
        "acceleration": 8,
        "tackling": 2,
        "pressing": 3,
        "stamina": 6,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Direct winger who takes on defenders and creates chances from wide areas.",
        "archetype": "Inverted winger"
      },
      "rating": 5.5,
      "slot": {
        "role": "LW",
        "x": 70,
        "y": 8
      }
    },
    {
      "id": "player_3631",
      "name": "Rodrygo",
      "fullName": "Rodrygo Silva de Goes",
      "age": 24,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 6,
        "vision": 4,
        "finishing": 5,
        "dribbling": 8,
        "speed": 6,
        "acceleration": 8,
        "tackling": 2,
        "pressing": 3,
        "stamina": 5,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Direct winger who takes on defenders and creates chances from wide areas.",
        "archetype": "Inside forward"
      },
      "rating": 5.3,
      "slot": {
        "role": "ST",
        "x": 80,
        "y": 37
      }
    },
    {
      "id": "player_3630",
      "name": "Kylian Mbappé",
      "fullName": "Kylian Mbappé Lottin",
      "age": 27,
      "preferredFoot": "left",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 4,
        "vision": 4,
        "finishing": 9,
        "dribbling": 5,
        "speed": 5,
        "acceleration": 7,
        "tackling": 1,
        "pressing": 4,
        "stamina": 5,
        "heading": 4,
        "strength": 7,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Clinical striker who thrives inside the penalty area.",
        "archetype": "Fox in the box"
      },
      "rating": 4.9,
      "slot": {
        "role": "RW",
        "x": 70,
        "y": 66
      }
    }
  ],
  "bench": [
    {
      "id": "player_3632",
      "name": "Vinícius Júnior",
      "fullName": "Vinícius José Paixão de Oliveira Júnior",
      "age": 25,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 4,
        "vision": 5,
        "finishing": 7,
        "dribbling": 5,
        "speed": 6,
        "acceleration": 6,
        "tackling": 1,
        "pressing": 4,
        "stamina": 5,
        "heading": 6,
        "strength": 6,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Powerful striker who holds the ball up and brings others into play.",
        "archetype": "Speed merchant"
      },
      "rating": 4.8
    },
    {
      "id": "player_3624",
      "name": "A. Tchouaméni",
      "fullName": "Aurélien Djani Tchouaméni",
      "age": 25,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 3,
        "dribbling": 4,
        "speed": 4,
        "acceleration": 6,
        "tackling": 5,
        "pressing": 4,
        "stamina": 7,
        "heading": 4,
        "strength": 6,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Mobile forward who can play across the front line.",
        "archetype": "Engine room"
      },
      "rating": 4.6
    },
    {
      "id": "player_3615",
      "name": "E. Camavinga",
      "fullName": "Eduardo Celmi Camavinga",
      "age": 23,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 5,
        "vision": 4,
        "finishing": 5,
        "dribbling": 6,
        "speed": 5,
        "acceleration": 7,
        "tackling": 2,
        "pressing": 2,
        "stamina": 4,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Skilful winger who combines dribbling ability with end product.",
        "archetype": "Direct winger"
      },
      "rating": 4.5
    },
    {
      "id": "player_3616",
      "name": "Dani Ceballos",
      "fullName": "Daniel Ceballos Fernández",
      "age": 29,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 2,
        "dribbling": 3,
        "speed": 3,
        "acceleration": 5,
        "tackling": 7,
        "pressing": 5,
        "stamina": 5,
        "heading": 4,
        "strength": 6,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "All-round midfielder who links defence and attack. Covers a lot of ground.",
        "archetype": "Deep-lying playmaker"
      },
      "rating": 4.5
    },
    {
      "id": "player_3618",
      "name": "Brahim Díaz",
      "fullName": "Brahim Abdelkader Díaz",
      "age": 26,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 3,
        "vision": 4,
        "finishing": 8,
        "dribbling": 4,
        "speed": 6,
        "acceleration": 6,
        "tackling": 1,
        "pressing": 4,
        "stamina": 4,
        "heading": 6,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Mobile forward who can play across the front line.",
        "archetype": "Speed merchant"
      },
      "rating": 4.5
    },
    {
      "id": "player_3604",
      "name": "Dani Carvajal",
      "fullName": "Daniel Carvajal Ramos",
      "age": 33,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 6,
        "vision": 3,
        "finishing": 2,
        "dribbling": 3,
        "speed": 4,
        "acceleration": 5,
        "tackling": 4,
        "pressing": 4,
        "stamina": 4,
        "heading": 3,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Quick full-back who overlaps and delivers crosses into the box.",
        "archetype": "Defensive full-back"
      },
      "rating": 3.9
    },
    {
      "id": "player_3596",
      "name": "A. Lunin",
      "fullName": "Andriy Lunin",
      "age": 26,
      "preferredFoot": "right",
      "positions": [
        "GK"
      ],
      "stats": {
        "passing": 3,
        "vision": 2,
        "finishing": 0,
        "dribbling": 0,
        "speed": 1,
        "acceleration": 2,
        "tackling": 1,
        "pressing": 1,
        "stamina": 3,
        "heading": 3,
        "strength": 3,
        "reflex": 6,
        "jump": 4
      },
      "profile": {
        "summary": "Commanding goalkeeper who organises the back line effectively.",
        "archetype": "Shot-stopper"
      },
      "rating": 3.8
    }
  ]
};

export const BARCELONA: Club = {
  "id": "529",
  "slug": "barcelona",
  "name": "Barcelona",
  "code": "BAR",
  "colors": [
    "#A50044",
    "#004D98"
  ],
  "logo": "logos/la_liga/barcelona.svg",
  "founded": 1899,
  "country": "Spain",
  "venue": {
    "name": "Camp Nou",
    "city": "Barcelona",
    "capacity": 55926,
    "surface": "grass"
  },
  "coach": {
    "id": 21131,
    "name": "R. Sanchez"
  },
  "starting11": [
    {
      "id": "player_3286",
      "name": "Joan García",
      "fullName": "Joan García Pons",
      "age": 24,
      "preferredFoot": "right",
      "positions": [
        "GK"
      ],
      "stats": {
        "passing": 3,
        "vision": 2,
        "finishing": 0,
        "dribbling": 1,
        "speed": 2,
        "acceleration": 2,
        "tackling": 1,
        "pressing": 1,
        "stamina": 3,
        "heading": 3,
        "strength": 3,
        "reflex": 7,
        "jump": 4
      },
      "profile": {
        "summary": "Reliable keeper with good reflexes and presence in the box.",
        "archetype": "Ball-playing keeper"
      },
      "rating": 4.2,
      "slot": {
        "role": "GK",
        "x": 5,
        "y": 37
      }
    },
    {
      "id": "player_3291",
      "name": "João Cancelo",
      "fullName": "João Pedro Cavaco Cancelo",
      "age": 31,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 6,
        "vision": 5,
        "finishing": 2,
        "dribbling": 5,
        "speed": 6,
        "acceleration": 6,
        "tackling": 5,
        "pressing": 5,
        "stamina": 6,
        "heading": 4,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Quick full-back who overlaps and delivers crosses into the box.",
        "archetype": "Modern full-back"
      },
      "rating": 5,
      "slot": {
        "role": "LB",
        "x": 18,
        "y": 11
      }
    },
    {
      "id": "player_3290",
      "name": "Alejandro Balde",
      "fullName": "Alejandro Balde Martínez",
      "age": 22,
      "preferredFoot": "left",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 6,
        "vision": 4,
        "finishing": 2,
        "dribbling": 5,
        "speed": 6,
        "acceleration": 7,
        "tackling": 4,
        "pressing": 4,
        "stamina": 5,
        "heading": 3,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Solid defender who gets forward to support attacks when possible.",
        "archetype": "Inverted full-back"
      },
      "rating": 4.8,
      "slot": {
        "role": "CB",
        "x": 22,
        "y": 28
      }
    },
    {
      "id": "player_3297",
      "name": "J. Koundé",
      "fullName": "Jules Olivier Koundé",
      "age": 27,
      "preferredFoot": "right",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 7,
        "vision": 4,
        "finishing": 2,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 6,
        "tackling": 5,
        "pressing": 4,
        "stamina": 6,
        "heading": 3,
        "strength": 5,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Energetic full-back who contributes at both ends of the pitch.",
        "archetype": "Wing-back"
      },
      "rating": 4.6,
      "slot": {
        "role": "CB",
        "x": 22,
        "y": 46
      }
    },
    {
      "id": "player_3298",
      "name": "Gerard Martín",
      "fullName": "Gerard Martín Langreo",
      "age": 23,
      "preferredFoot": "left",
      "positions": [
        "Defender"
      ],
      "stats": {
        "passing": 6,
        "vision": 4,
        "finishing": 1,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 6,
        "tackling": 4,
        "pressing": 4,
        "stamina": 6,
        "heading": 4,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Solid defender who gets forward to support attacks when possible.",
        "archetype": "Defensive full-back"
      },
      "rating": 4.3,
      "slot": {
        "role": "RB",
        "x": 18,
        "y": 63
      }
    },
    {
      "id": "player_3313",
      "name": "Lamine Yamal",
      "fullName": "Lamine Yamal Nasraoui Ebana",
      "age": 18,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 5,
        "vision": 4,
        "finishing": 5,
        "dribbling": 9,
        "speed": 7,
        "acceleration": 7,
        "tackling": 2,
        "pressing": 3,
        "stamina": 5,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Direct winger who takes on defenders and creates chances from wide areas.",
        "archetype": "Wide forward"
      },
      "rating": 5.3,
      "slot": {
        "role": "CDM",
        "x": 38,
        "y": 37
      }
    },
    {
      "id": "player_3315",
      "name": "Raphinha",
      "fullName": "Raphael Dias Belloli",
      "age": 29,
      "preferredFoot": "right",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 6,
        "vision": 5,
        "finishing": 6,
        "dribbling": 7,
        "speed": 6,
        "acceleration": 7,
        "tackling": 2,
        "pressing": 3,
        "stamina": 5,
        "heading": 2,
        "strength": 3,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Direct winger who takes on defenders and creates chances from wide areas.",
        "archetype": "Inside forward"
      },
      "rating": 5.3,
      "slot": {
        "role": "CM",
        "x": 50,
        "y": 24
      }
    },
    {
      "id": "player_3304",
      "name": "Fermín",
      "fullName": "Fermín López Martín",
      "age": 22,
      "preferredFoot": "left",
      "positions": [
        "Midfielder"
      ],
      "stats": {
        "passing": 6,
        "vision": 6,
        "finishing": 4,
        "dribbling": 4,
        "speed": 5,
        "acceleration": 5,
        "tackling": 4,
        "pressing": 5,
        "stamina": 6,
        "heading": 4,
        "strength": 4,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Clinical striker who thrives inside the penalty area.",
        "archetype": "Ball-winning midfielder"
      },
      "rating": 4.9,
      "slot": {
        "role": "CM",
        "x": 50,
        "y": 50
      }
    },
    {
      "id": "player_3310",
      "name": "R. Bardghji",
      "fullName": "Roony Bardghji",
      "age": 20,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 4,
        "vision": 5,
        "finishing": 4,
        "dribbling": 7,
        "speed": 6,
        "acceleration": 7,
        "tackling": 1,
        "pressing": 2,
        "stamina": 4,
        "heading": 2,
        "strength": 2,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Direct winger who takes on defenders and creates chances from wide areas.",
        "archetype": "Inside forward"
      },
      "rating": 4.5,
      "slot": {
        "role": "LW",
        "x": 70,
        "y": 8
      }
    },
    {
      "id": "player_3314",
      "name": "R. Lewandowski",
      "fullName": "Robert Lewandowski",
      "age": 37,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 3,
        "vision": 3,
        "finishing": 8,
        "dribbling": 4,
        "speed": 4,
        "acceleration": 4,
        "tackling": 1,
        "pressing": 4,
        "stamina": 4,
        "heading": 5,
        "strength": 6,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Powerful striker who holds the ball up and brings others into play.",
        "archetype": "Poacher"
      },
      "rating": 3.9,
      "slot": {
        "role": "ST",
        "x": 80,
        "y": 37
      }
    },
    {
      "id": "player_3316",
      "name": "M. Rashford",
      "fullName": "Marcus Rashford",
      "age": 28,
      "preferredFoot": "right",
      "positions": [
        "Forward"
      ],
      "stats": {
        "passing": 4,
        "vision": 3,
        "finishing": 7,
        "dribbling": 4,
        "speed": 4,
        "acceleration": 5,
        "tackling": 1,
        "pressing": 3,
        "stamina": 4,
        "heading": 5,
        "strength": 7,
        "reflex": 1,
        "jump": 1
      },
      "profile": {
        "summary": "Clinical striker who thrives inside the penalty area.",
        "archetype": "Fox in the box"
      },
      "rating": 3.9,
      "slot": {
        "role": "RW",
        "x": 70,
        "y": 66
      }
    }
  ],
  "bench": []
};
