import leagueSchedules from "@/Data/leagueSchedules.json";

export interface LeagueScheduleConfig {
  slug:            string;
  /** "MM-DD" template for season start */
  seasonStartMMDD: string;
  /** "MM-DD" template for season end */
  seasonEndMMDD:   string;
  /** true = end date is in year+1 (European leagues); false = same year (Brazilian) */
  crossYear:       boolean;
  /** Days of week matches are played: 0=Sun, 1=Mon, ..., 6=Sat */
  matchDays:       number[];
  /** Days to offset from season start before placing round 1, staggers leagues so they don't all play on same day */
  baseWeekOffset:  number;
}

/** Loaded from Data/leagueSchedules.json (generated by scripts/importOpenFootball.ts). */
export const LEAGUE_SCHEDULE_CONFIGS: LeagueScheduleConfig[] = leagueSchedules as LeagueScheduleConfig[];

/** Get start date string for a given calendar year */
export function leagueSeasonStart(config: LeagueScheduleConfig, year: number): string {
  return `${year}-${config.seasonStartMMDD}`;
}

/** Get end date string for a given calendar year */
export function leagueSeasonEnd(config: LeagueScheduleConfig, year: number): string {
  const endYear = config.crossYear ? year + 1 : year;
  return `${endYear}-${config.seasonEndMMDD}`;
}
